import type {Metadata} from "next";
import {Arimo, Heebo} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const heebo = Heebo({subsets: ["latin"]});
const arimo = Arimo({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={heebo.className}>
        <Navbar />
      
        {children}
      </body>
    </html>
  );
}
